[login info]
Page_URL = https://demo.wiseai.wiseyak.com/
Username_Input = NAME, username
Password_Input = NAME, password
Login_Button = XPATH,//button[@type='submit']
Profile= XPATH, //div[contains(text(), "Organization Overview")]
Toast_Alert = XPATH, //div[contains(@class,'Toastify__toast') and contains(@class,'Toastify__toast--error')]

[WiseAI Dashboard]
Create_New_User = XPATH, //a[contains(text(), "Create New User")]
Email = NAME, email
First_Name =NAME, first_name
Family_Name= NAME, family_name
Middle_Name = NAME, middle_name
Password = NAME, password
Create_Account = XPATH, //button[@type='submit']
Toast_Alert_Error = XPATH, //div[contains(@class,'Toastify__toast') and contains(@class,'Toastify__toast--error')]
Toast_Alert_Success = XPATH, //div[contains(@class,'Toastify__toast') and contains(@class,'Toastify__toast--success')]
#Error_Message_Div= XPATH, //div[contains(@class, "relative")]
#Error_Message= XPATH, .//span[contains(@class, "block text-xs")]
Email_Error_Message = XPATH, //input[@name='email']/ancestor::div[1]/following-sibling::span[contains(@class,'text-red-500')]
FirstName_Error_Message = XPATH, //input[@name='first_name']/ancestor::div[1]/following-sibling::span[contains(@class,'text-red-500')]
FamilyName_Error_Message = XPATH,//input[@name='family_name']/ancestor::div[1]/following-sibling::span[contains(@class,'text-red-500')]
Password_Error_Message = XPATH, //input[@name='password']/ancestor::div[1]/following-sibling::span[contains(@class,'text-red-500')]

[Assign Services]
Assign_Services_URL = https://demo.wiseai.wiseyak.com/assign-roles
Header = XPATH, //h1[contains(text(), 'Assign Services')]
All_Services =XPATH, //span[contains(@class, "font-semibold text-gray-700")]

[Annotation]
Annotation_Page_URL=https://demo.wiseai.wiseyak.com/speech-to-text/maithili/annotation
STT_Maithili= XPATH, //span[contains(text(), "STT - Maithili Annotation")]
Tokens_button = XPATH, //a[contains(text(), "Tokens")]
My_Task_button = XPATH, //a[contains(text(), "My Tasks")]
Pick_Tokens =XPATH, //button[contains(text(), "Pick")]
Pending_Task = XPATH, //span[contains(text(), "Pending")]
Pick_Successful = XPATH, //div[contains(text(), "Audio task picked successfully!")]
Pick_Task = XPATH, //td[contains(@class,'p-2 align-middle')]
Pick_Tokens_Auto = XPATH, (//button[normalize-space()='Pick Another Task'])[2]
Use_AI_Button = XPATH, //button[contains(text(), "Use AI")]
Transcription_Generation_Successful_Message = XPATH, //div[contains(text(), "Transcription generated successfully!")]
Submit_Task = XPATH, //button[contains(text(), "Submit")]
Next_Task = XPATH, (//button[normalize-space()='Next Task'])[2]
Remaining_Task = XPATH, //span[contains(@class, "text-sm font-semibold")]